//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgeteerApp1 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        private Gadgeteer.Modules.GHIElectronics.LightSensor lightSensor;
        
        private Gadgeteer.Modules.GHIElectronics.LightSensor lightSensor1;
        
        private Gadgeteer.Modules.GHIElectronics.MotorControllerL298 motorControllerL298;
        
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.lightSensor1 = new GTM.GHIElectronics.LightSensor(9);
            this.lightSensor = new GTM.GHIElectronics.LightSensor(10);
            this.motorControllerL298 = new GTM.GHIElectronics.MotorControllerL298(11);
        }
    }
}
